exclude: [
  "Gemfile",
  "Gemfile.lock",
  "Rakefile",
  "lib",
  "tasks",
  "spec",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "*.rb"
]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
