exclude: [
  "Gemfile",
  "Gemfile.lock",
  "Rakefile",
  "lib",
  "tasks",
  "spec",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "*.rb"
]

# Default frontmatter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Setup Jekyll Collections to organize site content
collections:
  # The 'software' collection is general documentation about software produced
  # by the Samvera community.
  software:
    output: true

  posts:
    output: true
    permalink: /blog/:categories/:title

collections_dir: site_content

publish:
  gh_pages_repo: git@github.com:afred/afred.github.io.git
